Staging
dansenpai/geladas pull request #1
Opened 2022-08-12 22:18 UTC by dnosuke

2022-08-12 22:50 UTC, dansenpai requested changes

2022-08-12 22:50 UTC, dansenpai commented on src/screens/Cart/index.tsx
> +                                    <Button size="6" variant="subtle" onPress={() => {
Nunca é bom passarmos funções anônimas como props assim, devemos sempre criar uma função no escopo do componente pra isso, mesmo que pareça redundante
```suggestion
                                    <Button size="6" variant="subtle" onPress={handleAddItemToCart}
```

2022-08-12 22:50 UTC, dansenpai commented on src/screens/Cart/index.tsx
> +                                <Text color="#46DE99" fontSize="xl" fontWeight="bold" >R$ {(price * quant).toFixed(2)}</Text>
Aqui é só questão de legibilidade, seria melhor criar uma variável lá em cima ou então criar uma função, talvez num arquivo chamado  `utils` na raiz do projeto, pra gente usar em outros lugares. 

* criar pasta utils,, dentro dela criar um arquivo que vai ter varias funções globais, por exemplo essa.

```suggestion
                                <Text color="#46DE99" fontSize="xl" fontWeight="bold" >{formatMoney(price * quant)}</Text>
```

2022-08-12 22:50 UTC, dansenpai commented on src/screens/Cart/index.tsx
> +                                <Text color="#46DE99" fontSize="xl" fontWeight="bold" >R$ {(price * quant).toFixed(2)}</Text>
A função formatMoney pode ser feita com a api do javascript  `Intl` é bem fácil de usar, ela já formata e adicionar o R$

2022-08-12 22:50 UTC, dansenpai commented on src/App.tsx
> +import Cart from "./screens/Cart";
Se tiver interessado em pesquisar um pouco, depois dá uma olhada em `import alias`.
É quando ao invés de colocar os pontos pra navegar nas pastas a gente usa tipo assim `@screens/cart`;
Desse jeito não precisa se preocupar onde está o componente, essa connfiguração é feita no `package.json`

2022-08-12 22:50 UTC, dansenpai commented on src/screens/ProductInfo/index.tsx
> +                                    <Button size="8" variant="subtle" onPress={() => {
mesma questão acima de não passar nada por funnção anônima assim

2022-08-12 22:51 UTC, dansenpai commented on src/screens/Cart/index.tsx
> +                                    <Button size="6" variant="subtle" onPress={() => {
Ahh, o motivo, é que sempre que a página é  re-renderizada ela declara a função novamente, usando mais memória assim

2022-08-13 17:19 UTC, dnosuke reviewed
ok

2022-08-13 17:29 UTC, dansenpai approved these changes

2022-08-13 18:54 UTC, merged